# Clash Mi 配置文件，适用iOS版。
# 更新日期：2026-09-05
# 使用说明：下载配置，并自行填写完善【机场区域】的机场订阅地址 https://


# ███████████████████████████ 机场区域 ███████████████████████████
proxy-providers:
  Airport1:
    url: "https://" #填写完整订阅地址
    type: http
    path: ./providers/Airport1.yaml
    interval: 86400  #订阅更新频率（秒）
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300


# ███████████████████████████ 锚点区域 ███████████████████████████

# ══ 订阅锚点 ══
Anchor_PR: &Anchor_PR {type: http, interval: 86400, proxy: DIRECT, health-check: {enable: true, url: 'https://www.gstatic.com/generate_204', interval: 300}, filter: "^(?!.*(到期|过期|剩余|网址|官网|邮箱|订阅|套餐|流量|说明|重置)).*$"}

# ══ 出站锚点 ══
Anchor_OB: &Anchor_OB {type: select, proxies: [默认代理, 香港自动, 日本自动, 新加坡自动, 美国自动, 香港手动, 日本手动, 新加坡手动, 美国手动, 手动选择, DIRECT, REJECT]}

# ══ 策略锚点 ══
Anchor_HS: &Anchor_HS {type: select, use: [Airport1]}
Anchor_FB: &Anchor_FB {type: fallback, use: [Airport1], url: 'https://www.gstatic.com/generate_204', interval: 300, lazy: true, timeout: 2000, max-failed-times: 3, hidden: true}
Anchor_UT: &Anchor_UT {type: url-test, use: [Airport1], url: 'https://www.gstatic.com/generate_204', interval: 600, lazy: true, tolerance: 50, timeout: 2000, max-failed-times: 3, hidden: true}

# ══ 规则锚点 ══
Anchor_DN: &Anchor_DN {type: http, interval: 86400, behavior: domain, format: mrs}
Anchor_DN_PROXY: &Anchor_DN_PROXY {type: http, interval: 86400, behavior: domain, format: mrs, proxy: 默认代理}
Anchor_IP: &Anchor_IP {type: http, interval: 86400, behavior: ipcidr, format: mrs, proxy: 默认代理}
Anchor_CL: &Anchor_CL {type: http, interval: 86400, behavior: classical, format: text}

# ══ 区域筛选锚点 ══

# 香港：兼容 香港 / 港 / HK / HKG / Hong Kong / Hong-Kong 等
Anchor_HK: &Anchor_HK '(?i)(香港|港|🇭🇰|HKG|\bHK\b|Hong[ _-]*Kong)'
# 日本：兼容 日本 / 日 / JP / JPN / Japan / Tokyo / Osaka 等
Anchor_JP: &Anchor_JP '(?i)(日本|日|🇯🇵|JPN|\bJP\b|Japan|Tokyo|东京|東京|Osaka|大阪|NRT|HND|KIX|CTS|FUK)'
# 新加坡：兼容 新加坡 / 狮城 / SG / SGP / Singapore
Anchor_SG: &Anchor_SG '(?i)(新加坡|狮城|獅城|🇸🇬|SGP|\bSG\b|Singapore)'
# 美国：兼容 美国 / 美 / US / USA / United States / 常见城市及机场代码
Anchor_US: &Anchor_US '(?i)(美国|美國|美|🇺🇸|USA|\bUS\b|United[ _-]*States|America|Los[ _-]*Angeles|San[ _-]*Jose|San[ _-]*Francisco|Seattle|Dallas|Chicago|New[ _-]*York|Washington|Miami|Atlanta|Phoenix|Denver|LAX|SJC|SFO|SEA|JFK|EWR|ORD|DFW|IAD|MIA|ATL)'
Anchor_OT: &Anchor_OT '^(?!.*(流量)).*$'


# ███████████████████████████ 核心配置 ███████████████████████████

# ══ 基础配置 ══
mode: rule                                                     # 工作模式 rule/global/direct
ipv6: false                                                    # 是否启用 IPv6
mixed-port: 7893                                               # HTTP + SOCKS5 混合代理端口
allow-lan: true                                                # 是否允许局域网设备连接
bind-address: "*"                                              # 监听所有接口
log-level: warning                                             # 日志级别
unified-delay: true                                            # 统一延迟
tcp-concurrent: true                                           # TCP 并发连接
profile: {store-selected: true, store-fake-ip: true}           # 保存策略选择和 Fake-IP


# ══ 管理面板 ══
external-ui-url: https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip
external-controller: 127.0.0.1:9090
external-ui-name: zashboard
external-ui: ui
secret: ""


# ══ TUN配置 ══
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - any:53
    - tcp://any:53
  auto-detect-interface: true
  auto-route: true
  auto-redirect: true
  strict-route: false
  endpoint-independent-nat: false


# ══ 嗅探功能 ══
sniffer:
  enable: true
  override-destination: true
  parse-pure-ip: true
  force-dns-mapping: true

  sniff:
    QUIC: {ports: [443]}
    TLS: {ports: [443, 8443]}
    HTTP: {ports: [80, 8080-8880], override-destination: true}

  force-domain:
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
#    - "+.tiktok.com"

  skip-domain:
    - "+.apple.com"
    - "+.mijia.cloud"
    - "+.io.mi.com"
    - "+.oray.com"
    - "+.sunlogin.net"
    - "+.push.apple.com"


# ══ DNS配置 ══
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:7874
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  respect-rules: false

  fake-ip-filter:
    - '+.lan'
    - '+.local'
    - "rule-set:cn_domain"
    - '+.market.xiaomi.com'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'

  nameserver:
    - 223.5.5.5
    - 119.29.29.29


# ███████████████████████████ 策略分组 ███████████████████████████

proxy-groups:

  # ══ 订阅组 ══
  - {name: 默认代理, type: select, proxies: [香港自动, 日本自动, 新加坡自动, 美国自动, 手动选择, DIRECT], icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Final.png}

  - {name: 手动选择, <<: *Anchor_HS, filter: *Anchor_OT, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Outside.png}


  # ══ 规则组 ══
  - {name: Google, <<: *Anchor_OB, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Google.png}

  - {name: Ai, <<: *Anchor_OB, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/OpenAI.png}

  - {name: Apple, <<: *Anchor_OB, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Apple.png}

  - {name: Spotify, <<: *Anchor_OB, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Spotify.png}

  - {name: Social, <<: *Anchor_OB, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Twitter.png}

  - {name: Games, <<: *Anchor_OB, icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Game.png}

  - {name: Netflix, <<: *Anchor_OB, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Netflix.png}

  - {name: Microsoft, <<: *Anchor_OB, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Microsoft.png}

  - {name: PayPal, <<: *Anchor_OB, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Paypal.png}

  - {name: Shield, <<: *Anchor_OB, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Reject.png}

  - {name: 漏网之鱼, <<: *Anchor_OB, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Filter/Proxy.png}


  # ══ 区域组 ══

  # 香港组
  - {name: 香港手动, <<: *Anchor_HS, filter: *Anchor_HK, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/HK02.png}

  - {name: 香港自动, <<: *Anchor_UT, filter: *Anchor_HK, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/HK02.png}


  # 美国组
  - {name: 美国手动, <<: *Anchor_HS, filter: *Anchor_US, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/US.png}

  - {name: 美国自动, <<: *Anchor_UT, filter: *Anchor_US, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/US.png}


  # 日本组
  - {name: 日本手动, <<: *Anchor_HS, filter: *Anchor_JP, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/JP.png}

  - {name: 日本自动, <<: *Anchor_UT, filter: *Anchor_JP, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/JP.png}


  # 新加坡组
  - {name: 新加坡手动, <<: *Anchor_HS, filter: *Anchor_SG, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/SG.png}

  - {name: 新加坡自动, <<: *Anchor_UT, filter: *Anchor_SG, icon: https://raw.githubusercontent.com/erdongchanyo/icon/main/Policy-Country/SG.png}


# ███████████████████████████ 规则匹配 ███████████████████████████

# 规则按命中率从高到低：
# 私密地址 → 国内直连 → 海外服务 → IP分流 → 兜底

rules:

  # 1. 直连优先
  - RULE-SET,private_domain,DIRECT
  - GEOIP,private,DIRECT,no-resolve


  # 2. 个性化匹配
  - DOMAIN-SUFFIX,unpkg.com,DIRECT
  - DOMAIN-SUFFIX,clashmi.app,默认代理
  - DOMAIN-SUFFIX,jsdelivr.net,DIRECT
  - DOMAIN-SUFFIX,xhscdn.com,DIRECT
  - DOMAIN-SUFFIX,overcast.fm,默认代理
  - DOMAIN-SUFFIX,overcast-cdn.com,默认代理
  - DOMAIN-SUFFIX,jpush.cn,默认代理


  # 3. 国内域名
  - RULE-SET,cn_domain,DIRECT


  # 4. AI优先，防风控
  - RULE-SET,ai_domain,Ai
  - DOMAIN-SUFFIX,searchgpt.com,Ai
  - IP-ASN,399358,Ai,no-resolve


  # 5. 特定海外服务域名分流
  - RULE-SET,apple_domain,Apple

  - RULE-SET,youtube_domain,Google
  - RULE-SET,google_domain,Google

  - RULE-SET,spotify_domain,Spotify

  - RULE-SET,whatsapp_domain,Social
  - RULE-SET,instagram_domain,Social
  - RULE-SET,facebook_domain,Social
  - RULE-SET,snapchat_domain,Social
  - RULE-SET,telegram_domain,Social
  - RULE-SET,twitter_domain,Social
  - RULE-SET,discord_domain,Social

  - RULE-SET,netflix_domain,Netflix
  - RULE-SET,paypal_domain,PayPal

  - RULE-SET,games_domain,Games
  - DOMAIN-SUFFIX,2ksports.com,Games
  - DOMAIN-SUFFIX,marketingcloudapis.com,Games

  - RULE-SET,github_domain,默认代理
  - RULE-SET,microsoft_domain,Microsoft


  # 6. 儿童保护
  - DOMAIN-SUFFIX,91porn.com,Shield
  - RULE-SET,porn_domain,Shield


  # 7. IP 分流
  - RULE-SET,google_ip,Google,no-resolve
  - RULE-SET,facebook_ip,Social,no-resolve
  - RULE-SET,telegram_ip,Social,no-resolve
  - RULE-SET,twitter_ip,Social,no-resolve
  - RULE-SET,netflix_ip,Netflix,no-resolve

  - RULE-SET,cn_ip,DIRECT,no-resolve


  # 8. 海外域名匹配兜底
  - RULE-SET,geolocation-!cn,默认代理


  # 9. 全局兜底
  - MATCH,漏网之鱼


# ███████████████████████████ 规则来源 ███████████████████████████

rule-providers:

  # ══ 域名规则 ══
  private_domain: {<<: *Anchor_DN, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}

  cn_domain: {<<: *Anchor_DN, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}


  # ══ AI组合 ══
  ai_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs"}


  # ══ 媒体 ══
  youtube_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}

  spotify_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs"}

  netflix_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}


  # ══ 常用 ══
  apple_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"}

  github_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}

  google_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}

  microsoft_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}

  paypal_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}


  # ══ 社交 ══
  whatsapp_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/whatsapp.mrs"}

  facebook_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/facebook.mrs"}

  instagram_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/instagram.mrs"}

  snapchat_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/snap.mrs"}

  telegram_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}

  twitter_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/twitter.mrs"}

  discord_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/discord.mrs"}


  # ══ 游戏组合 ══
  games_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games-!cn.mrs"}


  # ══ 儿童保护域名 ══
  porn_domain: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.mrs"}


  # ══ 海外域名合集 ══
  geolocation-!cn: {<<: *Anchor_DN_PROXY, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}


  # ══ IP规则 ══
  google_ip: {<<: *Anchor_IP, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}

  facebook_ip: {<<: *Anchor_IP, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.mrs"}

  telegram_ip: {<<: *Anchor_IP, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}

  twitter_ip: {<<: *Anchor_IP, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/twitter.mrs"}

  netflix_ip: {<<: *Anchor_IP, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}

  cn_ip: {<<: *Anchor_IP, url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}


# ███████████████████████████ 配置结束 ███████████████████████████
